#!/bin/bash

#SBATCH -n 1
#SBATCH --cpus-per-task=4
#SBATCH --time=10:30:30
#SBATCH --mem-per-cpu=4G
#SBATCH --tmp=4000                        # per node!!
#SBATCH --job-name="cifar_resnet_18_cpc"
#SBATCH --output="run1_cifar.out"
#SBATCH --error="run1_cifar.err"
#SBATCH --open-mode=truncate

module load python_gpu/3.8.5
python train_CPC.py --dataset cifar10 --epochs 100 --crop 30-0 --encoder resnet14 --norm none --grid_size 5 --pred_steps 3 --pred_directions 1
